drones_united/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/' => '_home#index'
  get '/about' => 'about#show'

  
  resources :locations

  resources :reviews

  

end 

drones_united/app/models/location.rb
class Location < ActiveRecord::Base 
	belongs_to :user
	has_many :reviews
end

drones_united/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :location
end

drones_united/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :locations

end 

drones_united/app/controllers/about_controller.rb
class AboutController < ApplicationController
	def show
		render "index"
	end 
end

drones_united/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
	def configure_permitted_parameters
	devise_parameter_sanitizer.for(:sign_up) << :name
	end
end

drones_united/app/controllers/enter_location_controller.rb
class EnterLocationController < ApplicationController
end

drones_united/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		render "index"
	end
end

drones_united/app/controllers/location_controller.rb
class LocationController < ApplicationController
	# has many :categories
	
	def index #to display all locations
		@locations = Location.all
	end 

	def show
		#render location 
		@location = Location.find(params[:id])	
	end

end

drones_united/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	# has many :categories
	
	def index #to display all locations
		@locations = Location.all
	end 

	def show
		#render location 
		@location = Location.find(params[:id])	
		@locationreviews = @location.reviews
		@review= Review.new
	end

end

drones_united/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :authenticate_user!, :only => [:new, :create]
	
	def index
		#will render all reviews
		render "index"
	end

	def new
		#will create a new review
  		@review = Review.new
	end

	def create
		@review = Review.new(params[:review])
		if @review.save
			redirect_to @user, alert:"User created successfully"
		else 
			redirect_to new_user_session_path, alert: "Error creating user."
		end 
	end
	
	def show
    	@users = User.find(params[:id])
	end
end

drones_united/app/helpers/about_helper.rb
module AboutHelper
end

drones_united/app/helpers/application_helper.rb
module ApplicationHelper
end

drones_united/app/helpers/home_helper.rb
module HomeHelper
end

drones_united/app/helpers/location_helper.rb
module LocationHelper
end

drones_united/app/helpers/review_helper.rb
module ReviewHelper
end

drones_united/app/views/home/index.html.erb
<main  role='main'>
    <div class="title_wrapper">
        <span class='index_title'> DRONES UNITED </span><br>
        <span class="index_motto">Spot your place in Miami</span>
    </div>
</main>


<div class="background">
    <div class="video-overlay">
        <video autoplay loop muted poster="media/background-drones_pic.img">
            <source src="assets/home_page.webm" type="video/webm">
            <source src="assets/home_page.mp4"  type="video/mp4">
        </video>
    </div>
</div>
<

drones_united/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drones United</title>
    
      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.mixitup/latest/jquery.mixitup.min.js"></script>
    <!-- Title main page "DRONES UNITED" -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,1000' rel='stylesheet' type='text/css'>


	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>


</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Home</a>
                                        
        </div>
          <ul class="nav navbar-nav">
            <li> <%= link_to 'Locations',locations_path %> </li>
            <li> <%= link_to 'Sign Up',new_user_registration_path %> </li>
            <li> <%= link_to 'Log in',new_user_session_path %> </li>
            <li> <%= link_to 'Sign Out',destroy_user_session_path, method: :delete %> </li>
            <li> <%= link_to 'About', '/about' %> </li>
            <li> <%= link_to '#noflyzone', '/about' %> </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <!-- renders everything for you in all other pages -->
  <%= yield %> 
</body>
</html>

drones_united/app/views/reviews/_index.html.erb
Hello 

drones_united/app/views/reviews/_new.html.erb
<!-- file for user to leave review --> 

<h1> Leave your review </h1>

<%= form_for(@review) do |f| %>
<%= f.text_field :name %>
<%= f.number_field :rating %>
<%= f.text_field :comment %>
<%= f.submit "Submit" %>
<% end %>