week_4/timetracking/config/routes.rb
Rails.application.routes.draw do

	get '/', to: 'site#home' #site is a controller
	get '/contact', to: 'site#contact'
	get '/say_name/:name', to: 'site#say_name'
	get '/calculator', to: 'site#calculator'
	post '/calculate', to: 'site#calculate'

  resource :projects, only: [:index, :show, :new, :create] do
    resource :time_entries, except: [:show]
  end 

end

week_4/timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :time_entries
	validates :names, presence: true #validation

	def self.clean_old
		old_projects = Project.where("created_at < ?", Time.now - 1.week)
		old_projects.destroy_all
	end
end

week_4/timetracking/app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
	belongs_to :project
end

week_4/timetracking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

week_4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.order(created_at: :desc).limit(10)
	end

	def show #name of the view
		@my_project = Project.find_by(params[:id])
		unless @my_project
		render "no_projects_found"
		end
	end

	def new
		@my_project = Project.new
		render 'new'
	end 

	def create
		@my_project = Project.new(
		:name => params[:project][:name],
		:description => params[:project][:description])
		@my_project.save

		redirect_to "/projects/#{@my_project.id}"
		#redirects user once they submits
	end 
end

week_4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController #inheritance
	def home
		render 'home' #name of the view template
	end

	def contact
		render 'contact'
	end

	def say_name
		@name = params[:name] #placeholder in the url parameter
		render 'say_name'
	end 

	def calculate
		@num1 = params [:first_num].to_f
		@num2 = params [:second_num].to_f
		@result = @num1 + @num2
		render 'calculate'
	end 
end

week_4/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def index
		@my_project = Project.find(params[:project_id])
		@my_entries = @my_project.time_entries
		render "index"
	end 

	def new
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.new
		render "new"
	end

	def create
		@my_project = Project.find params[:project_id]
		@my_entry = @my_project.time_entries.new(entry params)
			# hours: params[:time_entry][:hours],
			# minutes: params[:time_entry][:minutes],
			# date: params[:time_entry][:date])
		# redirect_to
		if @my_entry.save
			redirect_to action: "index", controller: "time_entries", project_id:
	project_id: @my_project.id 
		else
			render "new"
		end 		
	end

	def edit
		@my_project = Project.find params[:project_id]
		@my_entry = @my_project.time_entries.find params[:id]
	end

	def update
		@my_project = Project.find_by(id: params[:project_id]
		@my_entry = @my_project.time_entries.find_by(id: params[:id])
			if @my_entry.update(entry_params)
				redirect_to action: "index", controller: "time_entries",
		project_id: @my_project.id

			else
				render "edit"
			end
		end 
		
	end

	private

	def entry_params
		params.require(:time_entry).permit(:hours, :minutes, :date)
	end 








end

week_4/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week_4/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week_4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>

<%= yield %>

</body>
</html>

week_4/timetracking/app/views/time_entries/_form.html.erb
<% if @my_entry.errors.any? %>
	<% if flash [:error] %>
	<%= flash[:error] %>
<% end %>

<ul>
<% @my_entry.errors.full_messages.each do |error_msg| %>
	<li><%= error_msg %> </li>
<% end %>

</ul>
<% end %>
<%= form_for [@my_project, @my_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>
	<%= f.submit "Save" %>
	<%= link_to("Cancel", project_time_entries_path) %>

<% end %>

week_4/timetracking/app/views/time_entries/edit.html.erb
<%= form_for [@my_project, @my_entry] do |f| %>
	<% f.label :hours %>
	<%= f.text_field :hours, size: 4 %>
	<br>
	
	<%= f.label :minutes %>
	<%= f.text_field :minutes, size:4 %>
	<br>

	<%= f.label :date %>
	<%= f.date_field :date, size: 4 %>
	<br>

	<%= f.label :comments %>
	<%= f.text_area :comments %>
	<br>

	<%= f.submit "Save" %>
	<%= link_to "Cancel", project_time_entries_path(@my_project) %>

<h2> Edit time entry for <%= @my_project.name %> </h2>
<%= render "form" %>

<% end %>

week_4/timetracking/app/views/time_entries/index.html.erb
<h1><%= @my_project.name %></h1>

<ul>
<% @my_entries.each do |entry| %>
	<li>
		<%= entry.hours %> h
		<%= entry.minutes %> m -
		<%= entry.date %>
		<%= link_to "Edit", "/projects/#{@my_project.id}/ time_entries/#{entry.id}/edit" %>
		<!-- #add it so its in the loop -->
	</li>
<% end %>

</ul>

week_4/timetracking/app/views/time_entries/new.html.erb
<%= form_for [@my_project, @my_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
<br>

	<%= f.submit "Save" %>
<% end %>

<h2> Creating a new time entry in <%= @my_project.name %> project </h2>

<%= render "form" %>